---
- hosts: all
  remote_user: dev
  vars:
    ansistrano_deploy_from: "./"
    ansistrano_deploy_to: "/var/www/ongr"
    ansistrano_shared_paths: [var/logs, app/config/parameters.yml]
    ansistrano_keep_releases: 5
    ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/app/deploy/after-symlink.yml"
  roles:
    - { role: carlosbuenosvinos.ansistrano-deploy }
